# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SNMP-BridgeQuery
version:      0.6
version_from: BridgeQuery.pm
installdirs:  site
requires:
    Net::SNMP:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
